include/RandBLAS/dense_op.hh
src/dense_op.cc

This is a work around for Random123 bug using NVIDIA specific device side math library functions from host code.
resolves #8

define host side math functions for random123

---

CMake/version.cmake

Make git ignore tags that do not follow the semantic versioning format.
Note: a tag w/ semantic versioning format  should be added to the repo before/when this is merged. I suggest 0.1.0 pointing to the existing tag 19sept22

improve semantic versioning

---

INSTALL.md
include/RandBLAS/sjlts.hh
include/RandBLAS/util.hh
src/dense_op.cc
src/sjlts.cc
src/util.cc
test/src/test_sjlts.cc

Remove unsigned row and column index arrays in SJLTs, and in function signatures for dense operators.
Merging this will probably break RandLAPACK code, so I won't do so until a similar PR is staged for RandLAPACK.

No unsigned indexing

---

.github/workflows/core-linux.yaml
CMake/build_options.cmake
include/RandBLAS/sasos.hh
src/sasos.cc
test/src/test_sasos.cc

This also makes C++17 the explicit standard and moves RNG counters and keys into SASO structs.

Template numerical precision for SASOs

---

RandBLAS/CMakeLists.txt
RandBLAS/base.hh
RandBLAS/dense.hh
RandBLAS/random_gen.hh
RandBLAS/sparse.hh
test/CMakeLists.txt
test/test_dense.cc
test/test_rng_speed.cpp
test/test_sparse.cc

This PR supersedes PR #26. Big changes include:
* Added support for long-axis-sparse sketching operators, or "LASOs". Prior to this PR, we only supported short-axis-sparse operators, or "SASOs."
* Added support for transposes on the sketching operator and data matrix.
* Added support for "lifting" instead of just "sketching" with LSKGES and LSKGE3. More on this below.
* LSKGES previously had a helper function for sketching row-major data from the left with a (non-transposed) SASO. This PR removes that function. More on this below.
* Burlen's changes in PR #28 for improved templating of RNGState structs.
We used to have a requirement that ``B = op(S) * op(A)`` had fewer rows than ``op(A)``. That requirement is valid if we only allow proper sketching. However, there are situations where we …

Complete implementation of LSKGES

---

RandBLAS/test_util.hh
test/test_sparse.cc

This PR is a work in progress. I'll add a proper explanation once it's ready for review.
Need documentation for ...
* The new ``buffs_approx_equal`` function in ``RandBLAS/test_util.hh``.
* ``sparseskop_to_dense`` in ``test_sparse.cc``
* ``reference_lskges`` in ``test_sparse.cc``

Testing sparse sketching : use theoretical floating point error bounds to define tolerances

---

RandBLAS/dense.hh
rtd/source/API/index.rst
test/test_dense.cc

The ``DenseSkOp`` class has complicated semantics for memory management and lazy instantiation. These semantics have so far been governed by the ``persistent`` and ``filled`` members of ``DenseSkOp`` objects. In particular, the current implementation of LSKGE3 inspects these members and decides whether it needs to allocate memory and/or sample random numbers that define the sketching operator. The details of how this currently happens is not very relevant to this PR.
This PR **removes** the ``persistent`` and ``filled`` members of the ``DenseSkOp`` class.
This PR introduces a new function called ``realize_full`` that operates on ``DenseSkOp`` objects. Calling ``realize_full(S)`` populates ``S.buff`` as a matrix of size ``S.n_rows`` by ``S.n_cols`` in ``S.layout`` order. It also sets a …

Simplify DenseSkOp memory management semantics

---

RandBLAS/dense.hh
RandBLAS/sparse.hh
RandBLAS/test_util.hh
rtd/source/API/index.rst
test/test_dense.cc
test/test_sparse.cc

This PR implements right-sketching with dense and sparse operators. The implementations pass reasonably thorough tests. Documentation is included for right-sketching in a way that matches left-sketching.
This PR also simplifies a private helper function that's used with sparse sketching. The helper function's behavior was very complicated because it tried to avoid allocating memory. I've decided that for the sake of readability and simplicity, we should just _always_ allocate that memory. The effect of this change is that the new LSKGES and RSKGES have about double the workspace requirement of the old LSKGES.
To bring this point home, I'll note that this means our sparse and dense sketching operators have different memory management semantics. With dense sketching, it's possible to define …

Add support for sketching from the right : dense and sparse operators

---

.github/workflows/core-linux.yaml
.github/workflows/core-macos.yml
.github/workflows/openmp-macos.yaml
RandBLAS/dense.hh
RandBLAS/random_gen.hh
RandBLAS/sparse.hh
rtd/source/abstract_interface.rst
test/test_dense/test_construction.cc

Content of this PR:
* Changed ``blaspp_DIR`` used by CMake in GitHub Actions. This was necessary because blaspp recently changed the folder structure of their installation. Lapackpp presumably has undergone a similar change. We'll need to update RandLAPACK to reflect this. We might also need to update READMEs.
* Cosmetic changes (variable renaming) in ``dense.hh``.
* Renamed ``fill_dense_submat`` to be yet another overload of ``fill_dense``. The latter now has two overloads that populate user-provided buffers. These two overloads return a ``std::pair`` that we intend for the user to unpack with C++ structured bindings. The first element of this pair specifies the layout of the populated buffer. The second element is the updated random state.
* Wrote documentation for all ``fill_dense`` …

API change for fill_dense, plus fixes for Random123's sincospi on macOS.

---

RandBLAS/skge.hh

This adds an overload for ``sketch_general`` that makes it optional for the user to supply ``(i_off, j_off)`` for the sketching operator. If these aren't provided, then we dispatch a call to ``sketch_general`` that sets these values to zero.

sketch_general overload for (i_off, j_off) = (0, 0)

---

RandBLAS/skge.hh
test/test_dense/test_sketch_gefl3.cc

Created sketch_vector function in skge.hh and added unit test test_sketch_vec

Implementation of sketch_vector

---

examples/CMakeLists.txt
examples/TLS_DenseSkOp.cpp
examples/TLS_SparseSkOp.cpp

Inside the folder is a cmakelists.txt that requires RandBLAS, Blaspp, and Lapackpp. I have two implementations of TLS. One uses dense sketching and the other uses sparse sketching.

Added new folder for examples of sketching

---

RandBLAS/sparse_data/base.hh
RandBLAS/sparse_data/coo_matrix.hh
RandBLAS/sparse_data/coo_multiply.hh
RandBLAS/util.hh
test/CMakeLists.txt
test/common.hh
test/comparison.hh
test/linop_common.hh
test/test_dense/test_construction.cc
test/test_dense/test_sketch_gefl3.cc
test/test_dense/test_sketch_gefr3.cc
test/test_sketch_vector.cc
test/test_sparse_data/common.hh
test/test_sparse_data/test_coo.cc
test/test_sparse_data/test_csc.cc
test/test_sparse_data/test_csr.cc
test/test_sparse_data/test_left_multiply.cc
test/test_sparse_data/test_multiply.cc
test/test_sparse_data/test_right_multiply.cc
test/test_sparse_skops/test_construction.cc
test/test_sparse_skops/test_sketch_gefls.cc
test/test_sparse_skops/test_sketch_gefrs.cc

Namespace changes
* Move some sparse matrix datatypes into top-level ``RandBLAS::``.
* Remove the ``RandBLAS_Testing`` namespace (currently only used in ``RandBLAS/test_util.hh``; move code in that namespace to more appropriate files in ``test/..``.
Testing
* Write dedicated tests for sparse-times-dense matmul that don't rely on the tests for sparse sketching operators times dense matrices.
* Made code more readable by adding ``using`` statements (like ``using blas::Layout`` and ``using RandBLAS::SparseSkOp``) so namespaces don't need to be specified as much.

Add COOMatrix and other key classes/functions into RandBLAS namespace; write tests

---

.github/workflows/openmp-macos-13.yaml
.github/workflows/openmp-macos.yaml
RandBLAS/dense_skops.hh
test/test_dense_skops/test_construction.cc

The macos-openmp CI build has been failing lately. The error occurrs when trying to build blaspp:
```shell
Cloning into 'blaspp'...
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:[16](https://github.com/BallisticLA/RandBLAS/actions/runs/9229409689/job/25395565417?pr=89#step:4:17) (project):
The CMAKE_CXX_COMPILER:
/usr/local/opt/llvm/bin/clang++
is not a full path to an existing compiler tool.
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.
```
I'm pretty sure this stems from changes to the macos-latest GitHub Actions runner. When the failing builds install the LLVM toolchain, they report using …

Update macos-openmp GitHub actions workflow for macos-14 and higher

---

INSTALL.md
README.md
RandBLAS/DevNotes.md
rtd/source/index.rst

Update installation guide and have docs point to it

---

RandBLAS/base.hh
RandBLAS/config.h.in
RandBLAS/dense_skops.hh
RandBLAS/exceptions.hh
RandBLAS/random_gen.hh
RandBLAS/skge.hh
RandBLAS/sksy.hh
RandBLAS/skve.hh
RandBLAS/sparse_data/base.hh
RandBLAS/sparse_data/conversions.hh
RandBLAS/sparse_data/coo_matrix.hh
RandBLAS/sparse_data/coo_spmm_impl.hh
RandBLAS/sparse_data/csc_matrix.hh
RandBLAS/sparse_data/csc_spmm_impl.hh
RandBLAS/sparse_data/csr_matrix.hh
RandBLAS/sparse_data/csr_spmm_impl.hh
RandBLAS/sparse_data/sksp.hh
RandBLAS/sparse_data/spmm_dispatch.hh
RandBLAS/sparse_skops.hh
RandBLAS/util.hh
test/CMakeLists.txt
test/comparison.hh
test/test_basic_rng/rng_common.hh
test/test_basic_rng/test_sample_indices.cc
test/test_datastructures/test_denseskop.cc
test/test_datastructures/test_spmats/common.hh
test/test_matmul_cores/linop_common.hh
test/test_matmul_cores/test_spmm/spmm_test_helpers.hh

As usual, the scope of this PR exceeded my original plans.
I removed the include-guard pattern
```c++
#ifndef <file identifier>_hh
#define <file identifier>_hh
// ... code ...
#endif
```
and replaced it with ``#pragma once`` everywhere.
I added three functions to ``RandBLAS/util.hh``:
* sample_indices_iid: sample with replacement from an index set according to a (nonuniform) probability distribution, as specified by its cumulative distribution function.
* weights_to_cdf: converts a buffer of nonnegative numbers into a cumulative distribution function.
* sample_indices_iid_uniform: a more efficient version of sample_indices_iid, specialized to sampling from the uniform distribution.
I added a file
> test/test_basic_rng/rng_common.hh
This file is where we'll put code that's used to …

Infrastructure for Kolmogorov-Smirnov tests, (tested!) methods for sampling with replacement, and changes to include guards

---

RandBLAS/CMakeLists.txt
RandBLAS/base.hh
RandBLAS/compilers.hh
RandBLAS/dense_skops.hh
RandBLAS/exceptions.hh
RandBLAS/random_gen.hh
RandBLAS/skge.hh
RandBLAS/skve.hh
RandBLAS/sparse_skops.hh
RandBLAS/util.hh
examples/sparse-low-rank-approx/qrcp_matrixmarket.cc
examples/sparse-low-rank-approx/svd_matrixmarket.cc
examples/sparse-low-rank-approx/svd_rank1_plus_noise.cc
examples/total-least-squares/tls_dense_skop.cc
examples/total-least-squares/tls_sparse_skop.cc
rtd/source/api_reference/sketch_dense.rst
rtd/source/api_reference/utilities.rst
rtd/source/tutorial/index.rst
test/CMakeLists.txt
test/comparison.hh
test/test_basic_rng/test_r123.cc
test/test_datastructures/test_sparseskop.cc
test/test_exceptions.cc
test/test_handrolled_lapack.cc
test/test_io.cc

The PR title says most of what this changes. 
The most important change is that we disable compiler optimizations for Random123's Box-Muller transform and for our printing function. The former change was needed to resolve a failing test for RandLAPACK. The latter change is just to err on the side of caution.

Documentation for our Error class, improved printing utilities, and tests for both of these. Selected deactivation of compiler optimizations.

---

.gitignore
RandBLAS/base.hh
RandBLAS/dense_skops.hh
RandBLAS/sparse_skops.hh
RandBLAS/util.hh
rtd/source/api_reference/utilities.rst
rtd/source/updates/index.rst
test/test_basic_rng/test_discrete.cc
test/test_basic_rng/test_r123.cc
test/test_datastructures/test_sparseskop.cc

Changes since 1.0.0:
* Resolved #118.
* Resolved minor bugs in values of RNGState objects returned from sample_indices_iid and sample_indices_iid_uniform.
* Changed certain template defaults from ``r123::Philox4x32`` to ``DefaultRNG``.
* Replaced the RNGState constructor which previously accepted ``RNG::key_type::value_type`` to now accept``std::uint64_t``. This has the benefit of allowing any initial key for RandBLAS' default RNG, as opposed to only allowing keys of the form ``{k, 0}`` for some uint32 ``k``.
* Added ``sqrt_epsilon<T>()`` to the web documentation.
* Clarify that any functions which appear in the web documentation are part of our public API, for purposes of semantic versioning.

Release of RandBLAS 1.0.1: bugfixes for sampling from index sets

---

RandBLAS/sparse_data/conversions.hh
rtd/source/updates/index.rst
test/test_datastructures/test_spmats/test_csc.cc
test/test_datastructures/test_spmats/test_csr.cc

I'll add tests before merging this PR. But I want to note these necessary changes now as I'm discovering them.
A note: these functions were for converting from CSC or CSR format to COO format. Our examples which read sparse matrices from disk and run low-rank approximation algorithms were never unaffected. Those files only use conversions from COO to CSC or CSR.

Fix bugs in undocumented sparse matrix conversion functions

---

RandBLAS/sparse_data/base.hh
RandBLAS/sparse_data/conversions.hh
RandBLAS/sparse_data/coo_matrix.hh
RandBLAS/sparse_data/csc_matrix.hh
RandBLAS/sparse_data/csc_spmm_impl.hh
RandBLAS/sparse_data/csc_trsm_impl.hh
RandBLAS/sparse_data/csr_matrix.hh
RandBLAS/sparse_data/csr_spmm_impl.hh
RandBLAS/sparse_data/csr_trsm_impl.hh
RandBLAS/sparse_data/spmm_dispatch.hh
RandBLAS/sparse_data/trsm_dispatch.hh
rtd/source/api_reference/sketch_sparse.rst
test/test_sparse_trsm/test_sparse_trsm.cc

@PTNobel did fantastic work at the AMD Tools workshop on adding sparse trsm kernels to RandBLAS. This PR is to exposes those kernels to RandBLAS' public API.
Changes
* Add ``const`` qualifiers in sparse matrix format conversion functions.
* Add a utility function, ``compressed_indices_are_increasing``, to sparse_data/base.hh for use in checking assumptions in the new sparse trsm function.
* Fix minor documentation mistakes (arising from copy-pasting ...) in sparse_data/csc_matrix.hh.
* Add ``diag`` flags to sparse trsm kernels and ``nonunit`` flags to sparse trsv kernels. Remove redundant dimensional arguments from these kernels. In TRSM, change the variable used to refer to the number of right-hand-sides from "k" to "n" (and change the square matrix dimension from "n" to "m").
* Updated …

Adding sparse trsm to the public API
